config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root "static_pages#home"

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'

  post '/signup', to: 'users#create'

  get '/login', to: "sessions#new"

  post '/login', to: "sessions#create"

  delete '/logout', to: "sessions#destroy"

  get "slim_testings/test"

  get "slim_testings/index"

  resources :users do
    member do
      get :following, :followers
    end
  end 
  #onlyオプションをつけることで引数にしていしたアクションだけが追加される
  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :microposts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                :integer          not null, primary key
#  name              :string
#  email             :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  password_digest   :string
#  remember_digest   :string
#  admin             :boolean          default(FALSE)
#  activation_digest :string
#  activated         :boolean          default(FALSE)
#  activated_at      :datetime
#  reset_digest      :string
#  reset_sent_at     :datetime
#

class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
	attr_accessor :remember_token, :activation_token, :reset_token
	before_save :downcase_email
  before_create :create_activation_digest
	has_secure_password
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255},format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
	validates :password, presence: true, length: {minimum: 6}, allow_nil: true

	# 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #
  def self.new_token
  	SecureRandom.urlsafe_base64 #urlに渡される値がエスケープされない値を渡す
  end

  def remember
  	self.remember_token = User.new_token
  	update_attribute(:remember_digest, User.digest(remember_token))
  end

  #
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
  	BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil) #update_attribute系はコールバックがある&&updated_atが更新される(履歴が残る)
  end

#アカウントを有効化にする
  def activate
    update_columns(activated: true, activated_at: Time.zone.now) #update_columnsはコールバックがない(true,falseが返らない)&&updated_atが更新されない(履歴に残らない)
  end

#有効化用メールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

#パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

#パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

#パスワード再設定の機嫌が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end 

  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id) #id = self.id(インスタンスされたオブジェクトを見る)
  end

#ユーザーをフォローする
  def follow(other_user)
    following << other_user #フォローしているユーザーの配列を返した中にother_userを追加
  end

#フォローを解除
  def unfollow(other_user)
    self.active_relationships.find_by(followed_id: other_user.id).destroy 
    # 自分がフォローしているユーザーのレコード(follower_id = 自分のid, followed_id = other_user_id)を削除
    # SELECT * FROM "relationships" WHERE "follower_id" = user.id
  end

#
  def following?(other_user)
    following.include?(other_user) 
  end 

  private

    def downcase_email
      self.email.downcase!
    end 

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #"only:" = edit, updateアクションが走る前にlogged_in_userアクションを実行する
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  #全体表示
  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  #ユーザー単体ページ
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    redirect_to root_url and return unless @user.activated?
  end

  #新規登録ページ
  def new
  	@user = User.new
  end

  #新規登録処理
  def create 
  	@user = User.new(user_params) #test内でassigns(:user)でコントローラー内のuserインスタンスを見るために@をつけた
  	if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
  	else
  		render 'new'
  	end
  end

  #ユーザー編集ページ
  def edit
    @user = User.find(params[:id])
  end

  #ユーザー編集処理
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User Deleted"
    redirect_to users_url
  end

  def following 
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
    	params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    #beforeアクション 

    #正しいユーザーか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to root_url unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, size: 80) 
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/users/_follow.html.slim
= form_for(current_user.active_relationships.build, remote: true) do |f|
	= hidden_field_tag :followed_id, @user.id
	= f.submit "Follow", class: "btn btn-primary"

app/views/users/_follow_form.html.slim
- unless current_user?(@user)
  = react_component('follow_button', user: @user.attributes, relationship: current_user.active_relationships.find_by(followed_id: @user.id)&.attributes)

app/views/users/_form.html.slim
= form_for(@user, url: yield(:url)) do |f|
  = render "shared/error_messages", object: f.object

  = f.label :name
  = f.text_field :name, class: "form-control"

  = f.label :email
  = f.email_field :email, class: "form-control"

  = f.label :password
  = f.password_field :password, class: "form-control"

  = f.label :password_confirmation
  = f.password_field :password_confirmation, class: "form-control"

  = f.submit yield(:button_text), class: "btn btn-primary"

app/views/users/_unfollow.html.slim
= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete}, remote: true) do |f|
	= f.submit "Unfollow", class: "btn btn-danger"

app/views/users/_user.html.slim
li 
	= gravatar_for user, size: 50
	= link_to user.name, user
	- if current_user.admin? && !current_user?(user)
	  '| 
	  = link_to "delete", user, method: :delete, data: {confirm: "You sure?"}

app/views/users/edit.html.slim
- provide(:title, "Edit user")
- provide(:button_text, "Save changes")
- provide(:url, user_path(@user))
h1 Update your profile
.row
	.col-md-6.col-md-offset-3
	= render "form"
	.gravatar_edit
		= gravatar_for @user
		a href="http://gravatar.com/emails" target="_blank" rel="noopener" change

app/views/users/index.html.slim
- provide(:title, "All users")
h1 All users
= will_paginate
ul.users
	= render @users
= will_paginate

app/views/users/new.html.slim
- provide(:title, "Sign up")
- provide(:button_text, "Create my account")
- provide(:url, signup_path)
h1 Sign up
.row
	.col-md-6.col-md-offset-3
		= render "form"

app/views/users/show.html.slim
- provide(:title, @user.name)
.row
  aside.col-md-4
    section.user_info
      h1
        = gravatar_for @user
        = @user.name
    section.stats
      = render "shared/stats"
  .col-md-8
    = render "follow_form" if logged_in?
    - if @user.microposts.any?
      h3 microposts (#{@user.microposts.count})
      ol.microposts
        = render @microposts
      = will_paginate @microposts

app/views/users/show_follow.html.slim
- provide(:title, @title)
.row
	aside.col-md-4
		section.user_info
			= gravatar_for @user
			h1 #{@user.name}
			span #{link_to "view my profile", @user}
			span <b>Microposts:</b> #{@user.microposts.count}
		section.stats
			= render "shared/stats"
			- if @users.any?
				.user_avatars
					- @users.each do |user|
						= link_to gravatar_for(user, size: 30), user
	.col-md-8
		h3 #{@title}
		- if @users.any?
			ul.users.follow
				= render @users
			= will_paginate 